/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}", "./index.html"],
  theme: {
    extend: {
      animation: {
        spin: 'spin 1s linear infinite',
      },
      keyframes: {
        spin: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      colors: {
        "gray-scale30": "var(--gray-scale30)",
        "gray-scalebk": "var(--gray-scalebk)",
        "gray-scalegray-scale-100": "var(--gray-scalegray-scale-100)",
        "gray-scalegray-scale-200": "var(--gray-scalegray-scale-200)",
        "gray-scalegray-scale-300": "var(--gray-scalegray-scale-300)",
        "gray-scalegray-scale-400": "var(--gray-scalegray-scale-400)",
        "gray-scalegray-scale-50": "var(--gray-scalegray-scale-50)",
        "gray-scalegray-scale-500": "var(--gray-scalegray-scale-500)",
        "gray-scalegray-scale-600": "var(--gray-scalegray-scale-600)",
        "gray-scalegray-scale-700": "var(--gray-scalegray-scale-700)",
        "gray-scalegray-scale-800": "var(--gray-scalegray-scale-800)",
        "gray-scalegray-scale-900": "var(--gray-scalegray-scale-900)",
        "gray-scalewhite": "var(--gray-scalewhite)",
        "primaryprimary-100": "var(--primaryprimary-100)",
        "primaryprimary-200": "var(--primaryprimary-200)",
        "primaryprimary-300": "var(--primaryprimary-300)",
        "primaryprimary-400": "var(--primaryprimary-400)",
        "primaryprimary-50": "var(--primaryprimary-50)",
        "primaryprimary-500": "var(--primaryprimary-500)",
        "primaryprimary-600": "var(--primaryprimary-600)",
        "primaryprimary-700": "var(--primaryprimary-700)",
        "primaryprimary-800": "var(--primaryprimary-800)",
        "primaryprimary-900": "var(--primaryprimary-900)",
      },
      fontFamily: {
        "300": "var(--300-font-family)",
        "body-b1-100": "var(--body-b1-100-font-family)",
        "body-b1-200": "var(--body-b1-200-font-family)",
        "body-b2-100": "var(--body-b2-100-font-family)",
        "body-b2-200": "var(--body-b2-200-font-family)",
        "body-b2-300": "var(--body-b2-300-font-family)",
        "body-b3-100": "var(--body-b3-100-font-family)",
        "body-b3-200": "var(--body-b3-200-font-family)",
        "body-b4-100": "var(--body-b4-100-font-family)",
        "caption-01-100": "var(--caption-01-100-font-family)",
        "caption-01-200": "var(--caption-01-200-font-family)",
        "display-large": "var(--display-large-font-family)",
        "heading-h1-100": "var(--heading-h1-100-font-family)",
        "heading-h1-200": "var(--heading-h1-200-font-family)",
        "heading-h2-100": "var(--heading-h2-100-font-family)",
        "heading-h2-200": "var(--heading-h2-200-font-family)",
        "heading-h2-300": "var(--heading-h2-300-font-family)",
        "heading-h3-100": "var(--heading-h3-100-font-family)",
        "heading-h3-200": "var(--heading-h3-200-font-family)",
        "heading-h3-300": "var(--heading-h3-300-font-family)",
      },
    },
  },
  plugins: [],
};
