import type { JobPosting, UserProfile } from '../types';

// Mock data for development
export const mockJobPostings: JobPosting[] = [
  {
    id: '1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    createdByUserId: 'user1',
    title: '스타트업 UI/UX 디자이너 모집',
    company: '테크스타트업',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-02-28'),
    description: '사용자 경험을 중시하는 디자이너를 찾습니다. 모바일 앱과 웹 서비스의 UI/UX 디자인을 담당하게 됩니다.',
    recruitCount: 2,
    positions: '디자이너, UI/UX',
    requirements: 'Figma, Sketch 능숙자, 포트폴리오 필수',
    category: 'Design',
    viewCount: 124,
  },
  {
    id: '2',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    createdByUserId: 'user2',
    title: '마케팅 인턴 채용',
    company: '글로벌마케팅',
    startDate: new Date('2024-02-05'),
    endDate: new Date('2024-03-05'),
    description: '디지털 마케팅 전략 수립 및 실행을 함께할 인턴을 모집합니다. SNS 마케팅 경험자 우대합니다.',
    recruitCount: 3,
    positions: '마케터, 콘텐츠 기획자',
    requirements: 'SNS 마케팅 경험, 데이터 분석 능력',
    category: 'Marketing',
    viewCount: 89,
  },
  {
    id: '3',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
    createdByUserId: 'user3',
    title: '프론트엔드 개발자 구합니다',
    company: '웹에이전시',
    startDate: new Date('2024-02-10'),
    endDate: new Date('2024-12-31'),
    description: 'React 기반의 웹 애플리케이션 개발을 담당할 프론트엔드 개발자를 찾습니다.',
    recruitCount: 1,
    positions: '프론트엔드 개발자',
    requirements: 'React, TypeScript, 3년 이상 경력',
    category: 'IT',
    viewCount: 256,
  },
  {
    id: '4',
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
    createdByUserId: 'user4',
    title: '서비스 기획자 모집',
    company: '플랫폼컴퍼니',
    startDate: new Date('2024-02-15'),
    endDate: new Date('2024-03-15'),
    description: '새로운 서비스 기획 및 운영을 담당할 기획자를 모집합니다. 사용자 리서치 경험 필수입니다.',
    recruitCount: 2,
    positions: '서비스 기획자, PM',
    requirements: '서비스 기획 경험 2년 이상, 데이터 분석 능력',
    category: 'Planning',
    viewCount: 178,
  },
  {
    id: '5',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
    createdByUserId: 'user5',
    title: '그래픽 디자이너 채용',
    company: '크리에이티브스튜디오',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-03-20'),
    description: '브랜드 아이덴티티 및 마케팅 콘텐츠 디자인을 담당할 그래픽 디자이너를 찾습니다.',
    recruitCount: 1,
    positions: '그래픽 디자이너',
    requirements: 'Photoshop, Illustrator 능숙, 포트폴리오 필수',
    category: 'Design',
    viewCount: 92,
  },
];

export const mockUserProfiles: UserProfile[] = [
  {
    id: 'profile1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    createdByUserId: 'user1',
    university: '서울대학교',
    department: '디자인학과',
    bio: '사용자 중심의 디자인을 추구하는 디자이너입니다.',
  },
  {
    id: 'profile2',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
    createdByUserId: 'user2',
    university: '연세대학교',
    department: '경영학과',
    bio: '데이터 기반 마케팅 전략을 좋아합니다.',
  },
];
